#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# Dynamically figure out to use Docker Compose v1 or Docker Compose v2.
docker_compose="docker-compose"
if ! command -v "${docker_compose}"; then
  docker_compose="docker compose"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  ${docker_compose} "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  ${docker_compose} build
  ${docker_compose} run ${TTY} "${@}"
  ${docker_compose} down
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the web container
  _dc web "${@}"
}

function mix {
  # Run any mix commands
  cmd mix "${@}"
}

function iex {
  # Connect to an IEx session
  cmd iex -S mix
}

function secret {
  # Generate a random secret that can be used for secret keys and more
  mix phx.gen.secret
}

function lint:dockerfile {
  # Lint Dockerfile
  docker container run --rm -i \
    hadolint/hadolint hadolint --ignore DL3008 "${@}" - < Dockerfile
}

function lint {
  # Lint Elixir code
  mix credo
}

function format {
  # Run the mix formatter
  mix format
}

function format:check {
  # Check to see if there's an unformatted code
  format --check-formatted
}

function test {
  # Run test suite
  _dc -e "MIX_ENV=test" web mix test "${@}"
}

function test:coverage {
  # Get test coverage
  _dc -e "MIX_ENV=test" web mix coveralls "${@}"
}

function test:coverage:details {
  # Get test coverage details
  _dc -e "MIX_ENV=test" web mix coveralls.detail "${@}"
}

function shell {
  # Start a shell session in the web container
  cmd bash "${@}"
}

function psql {
  # Connect to PostgreSQL
  # shellcheck disable=SC1091
  . .env
 _dc postgres psql -U "${POSTGRES_USER}" "${@}"
}

function mix:install {
  # Install mix dependencies and write lock file
  _build_run_down web mix deps.get
}

function mix:outdated {
  # List any installed packages that are outdated
  mix hex.outdated
}

function yarn:install {
  # Install yarn dependencies and write lock file
  _build_run_down js yarn install
}

function yarn:outdated {
  # List any installed packages that are outdated
  _dc js yarn outdated
}

function yarn:build:js {
  # Build JS assets, this is meant to be run from within the assets container
  mkdir -p ../priv/static/js
  node esbuild.config.js
}

function yarn:build:css {
  # Build CSS assets, this is meant to be run from within the assets container
  local args=()

  if [ "${NODE_ENV:-}" == "production" ]; then
    args=(--minify)
  else
    args=(--watch)
  fi

  mkdir -p ../priv/static/css
  tailwindcss --postcss -i css/app.css -o ../priv/static/css/app.css "${args[@]}"
}

function prod:migrate {
  # Run database migrations in production
  cmd bin/hello eval "Hello.Release.migrate"
}

function prod:remote {
  # Connect an IEx session to your production system
  cmd bin/hello remote
}

function clean {
  # Remove cache and other machine generates files
  rm -rf priv/static/*.* priv/static/js priv/static/css priv/static/images priv/static/fonts
  touch priv/static/.keep
}

function ci:install-deps {
  # Install Continuous Integration (CI) dependencies
  sudo apt-get install -y curl shellcheck
  sudo curl \
    -L https://raw.githubusercontent.com/nickjj/wait-until/v0.2.0/wait-until \
    -o /usr/local/bin/wait-until && sudo chmod +x /usr/local/bin/wait-until
}

function ci:test {
  # Execute Continuous Integration (CI) pipeline
  #
  # It's expected that your CI environment has these tools available:
  #   - https://github.com/koalaman/shellcheck
  #   - https://github.com/nickjj/wait-until
  shellcheck run bin/*
  lint:dockerfile "${@}"

  cp --no-clobber .env.example .env
  cp --no-clobber docker-compose.override.yml.example docker-compose.override.yml

  ${docker_compose} build
  ${docker_compose} up -d

  # shellcheck disable=SC1091
  . .env
  wait-until "${docker_compose} exec -T \
    -e PGPASSWORD=${POSTGRES_PASSWORD} postgres \
    psql -U ${POSTGRES_USER} ${POSTGRES_USER} -c 'SELECT 1'"

  lint
  format:check
  mix ecto.setup
  test "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
