#!/usr/bin/env bash

set -eo pipefail

DC="${DC:-exec}"

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker-compose "${DC}" ${TTY} "${@}"
}

function _build_run_down {
  docker-compose build
  docker-compose run ${TTY} "${@}"
  docker-compose down
}

# -----------------------------------------------------------------------------

function cmd {
  # Run any command you want in the web container
  _dc web "${@}"
}

function mix {
  # Run any mix commands
  cmd mix "${@}"
}

function iex {
  # Connect to an IEx session
  cmd iex -S mix
}

function secret {
  # Generate a random secret that can be used for secret keys and more
  mix phx.gen.secret
}

function format {
  # Run the mix formatter
  mix format
}

function format:check {
  # Check to see if there's an unformatted code
  format --check-formatted
}

function credo {
  # Run credo to analyze your code base
  mix credo
}

function test {
  # Run test suite
  _dc -e "MIX_ENV=test" web mix test "${@}"
}

function coveralls {
  # Get test coverage with coveralls
  _dc -e "MIX_ENV=test" web mix coveralls "${@}"
}

function coveralls:detail {
  # Get test coverage details with coveralls
  _dc -e "MIX_ENV=test" web mix coveralls.detail "${@}"
}

function bash {
  # Start a Bash session in the web container
  cmd bash "${@}"
}

function psql {
  # Connect to PostgreSQL with psql
  # shellcheck disable=SC1091
  . .env
 _dc postgres psql -U "${POSTGRES_USER}" "${@}"
}

function mix:install {
  # Install mix dependencies and write lock file
  _build_run_down web mix deps.get
}

function mix:outdated {
  # List any installed packages that are outdated
  mix hex.outdated
}

function yarn:install {
  # Install yarn dependencies and write lock file
  _build_run_down webpack yarn install
}

function yarn:outdated {
  # List any installed packages that are outdated
  _dc webpack yarn outdated
}

function prod:migrate {
  # Run database migrations in production
  cmd bin/hello eval "Hello.Release.migrate"
}

function prod:remote {
  # Connect an IEx session to your production system
  cmd bin/hello remote
}

function clean {
  # Remove cache and other machine generates files
  rm -rf priv/static/*
  touch priv/static/.keep
}

function ci:install-deps {
  # Install Continuous Integration (CI) dependencies
  sudo apt-get install -y curl shellcheck
  sudo curl \
    -L https://raw.githubusercontent.com/nickjj/wait-until/v0.1.2/wait-until \
    -o /usr/local/bin/wait-until && sudo chmod +x /usr/local/bin/wait-until
}

function ci:test {
  # Execute Continuous Integration (CI) pipeline
  #
  # It's expected that your CI environment has these tools available:
  #   - https://github.com/koalaman/shellcheck
  #   - https://github.com/nickjj/wait-until
  shellcheck run bin/*

  cp --no-clobber .env.example .env
  cp --no-clobber docker-compose.override.yml.example docker-compose.override.yml

  docker-compose build
  docker-compose up -d

  # shellcheck disable=SC1091
  . .env
  wait-until "docker-compose exec -T \
    -e PGPASSWORD=${POSTGRES_PASSWORD} postgres \
    psql -U ${POSTGRES_USER} ${POSTGRES_USER} -c 'SELECT 1'"

  format:check
  mix ecto.setup
  test "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
